spring:
  profiles:
    active:
      - 8081
---
spring:
  profiles: 8081
  application:
    name: order-server
eureka:
  client:
    service-url:
      defaultZone: http://eureka8761.com:8761/eureka/,http://eureka8762.com:8762/eureka/,http://eureka8763.com:8763/eureka/,http://eureka8888.com:8888/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    app-group-name: hualisheng
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8081
---
spring:
  application:
    name: order-server
  profiles: 8089
eureka:
  client:
    service-url:
      defaultZone: http://eureka8761.com:8761/eureka/,http://eureka8762.com:8762/eureka/,http://eureka8763.com:8763/eureka/,http://eureka8888.com:8888/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    app-group-name: hualisheng
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8089
---
spring:
  application:
    name: order-server
  profiles: 8088
eureka:
  client:
    service-url:
      defaultZone: http://eureka8761.com:8761/eureka/,http://eureka8762.com:8762/eureka/,http://eureka8763.com:8763/eureka/,http://eureka8888.com:8888/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    app-group-name: hualisheng
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8088