spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev
  application:
    name: order-server
eureka:
  client:
    server-url:
      defaultZone: http://eureka8761.com:8761/eureka/,http://eureka8762.com:8762/eureka/,http://eureka8763.com:8763/eureka/,http://eureka8888.com:8888/eureka/
server:
  port: 8201
---
spring:
  application:
    name: order-server
  profiles: test
eureka:
  client:
    server-url:
      defaultZone: http://eureka8761.com:8761/eureka/,http://eureka8762.com:8762/eureka/,http://eureka8763.com:8763/eureka/,http://eureka8888.com:8888/eureka/
server:
  port: 8202