spring:
  application:
    name: consumer-server
  profiles:
    active:
      - dev
server:
  port: 8981
eureka:
  instance:
    instance-id: consumer-server
---
spring:
  profiles: dev
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka8761.com:8761/eureka/,http://eureka8762.com:8762/eureka/,http://eureka8763.com:8763/eureka/,http://eureka8888.com:8888/eureka/
---
spring:
  profiles: test
eureka:
  client:
    service-url:
      defaultZone: http://eureka8761.com:8761/eureka/,http://eureka8762.com:8762/eureka/,http://eureka8763.com:8763/eureka/,http://eureka8888.com:8888/eureka/